ALTER TABLE IF EXISTS cowork_approvals
  ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  ADD COLUMN IF NOT EXISTS claimed_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS claimed_by TEXT;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_constraint
    WHERE conname = 'cowork_approvals_id_unique'
  ) THEN
    ALTER TABLE cowork_approvals
      ADD CONSTRAINT cowork_approvals_id_unique UNIQUE (id);
  END IF;
END $$;

ALTER TABLE cowork_approvals
  DROP CONSTRAINT IF EXISTS cowork_approvals_state_check;

ALTER TABLE cowork_approvals
  ADD CONSTRAINT cowork_approvals_state_check
  CHECK (state IN ('requested', 'claimed', 'consumed', 'failed', 'ignored'));

CREATE INDEX IF NOT EXISTS idx_cowork_approvals_state_updated_at
  ON cowork_approvals (state, updated_at DESC);

CREATE INDEX IF NOT EXISTS idx_cowork_approvals_task_state
  ON cowork_approvals (task_id, state);
